### ISSUE TITLE
missing color files defined in deploy.sh

### ISSUE THREAD

**Issue by zetsub0u** [rmariano/vim-config#8]
wget -O $SYNTAX_DIR/python.vim $REPO_URL/$BRANCH/syntax/python.vim
wget -O $SYNTAX_DIR/Dockerfile.vim $REPO_URL/$BRANCH/syntax/Dockerfile.vim

This 2 files don't appear to be in the repo

**Comment by rmariano** [comment]
@zetsub0u I think the files should be available at https://github.com/rmariano/vim-config/tree/master/syntax
However I'm curious about how you found the error. Might this be happening? Why was it closed?

**Comment by zetsub0u** [comment]
At first i thought the files weren't there (looked in the wrong
directory) then i realized the problem was that the branch was wrong and in
fact the files were there. That's why i closed it.
