### ISSUE TITLE
deploy.sh script does not work with sh

### ISSUE THREAD

**Issue by zetsub0u** [rmariano/vim-config#9]
I had to do bash deploy.sh so the instant one-liner didn't work

Installing develop . Getting the latest version from https://raw.github.com/rmariano/vim-config
/tmp/deploy.sh: 11: /tmp/deploy.sh: [[: not found
/tmp/deploy.sh: 11: /tmp/deploy.sh: [[: not found

**Comment by rmariano** [comment]
@zetsub0u thanks for reporting! I will address this shortly.
